#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_SCREEN_WIDTH 800
#define CONFIG_SCREEN_HEIGHT 800

#define CONFIG_TIMER_TEXT_SIZE 256
#define CONFIG_STATE_TEXT_SIZE 40
#define CONFIG_TEXT_COLOR BLACK

#define CONFIG_WORK_BACKGROUND_COLOR SKYBLUE
#define CONFIG_WORK_BACKGROUND_COLOR_PAUSED DARKBLUE
#define CONFIG_REST_BACKGROUND_COLOR GREEN
#define CONFIG_REST_BACKGROUND_COLOR_PAUSED DARKGREEN
#define CONFIG_WORK_MINUTES 25
#define CONFIG_REST_MINUTES 5
#define CONFIG_START_RESTING true

#define CONFIG_RING_SOUND_PATH "ring.mp3"
#define CONFIG_NOISE_SOUND_PATH "noise.mp3"

#endif // CONFIG_H
